import os

from langchain_ollama import ChatOllama

from src.agent.prompts import (
    build_report_messages,
    build_sql_messages,
)

DEFAULT_MODEL = "qwen2.5-coder:7b"
DEFAULT_BASE_URL = "http://127.0.0.1:11434"


def extract_sql(content: str) -> str:
    """
    Normalize SQL generated by the local LLM.

    The prompt requests SQL-only output, but local models may
    occasionally wrap SQL in Markdown code fences.
    """

    sql = content.strip()

    if not sql:
        raise ValueError(
            "LLM returned an empty response."
        )

    if sql.startswith("```") and sql.endswith("```"):
        lines = sql.splitlines()

        if len(lines) >= 3:
            lines = lines[1:-1]
            sql = "\n".join(lines).strip()

    if not sql:
        raise ValueError(
            "No SQL found in LLM response."
        )

    return sql


class LocalSQLGenerator:
    """
    Generate SQLite queries using a local Ollama model.
    """

    def __init__(
        self,
        model: str | None = None,
        base_url: str | None = None,
        temperature: float = 0.0,
    ) -> None:
        self.model = (
            model
            or os.getenv("OLLAMA_MODEL")
            or DEFAULT_MODEL
        )

        self.base_url = (
            base_url
            or os.getenv("OLLAMA_BASE_URL")
            or DEFAULT_BASE_URL
        )

        self.llm = ChatOllama(
            model=self.model,
            base_url=self.base_url,
            temperature=temperature,
        )

    def generate_sql(
        self,
        question: str,
        schema_context: str,
        correction_feedback: str | None = None,
    ) -> str:
        messages = build_sql_messages(
            question=question,
            schema_context=schema_context,
            correction_feedback=correction_feedback,
        )

        response = self.llm.invoke(messages)

        content = response.content

        if not isinstance(content, str):
            raise TypeError(
                "Expected string content from Ollama."
            )

        return extract_sql(content)


class LocalBusinessReportGenerator:
    """
    Generate a business-friendly report from the
    actual SQL execution result.
    """

    def __init__(
        self,
        model: str | None = None,
        base_url: str | None = None,
        temperature: float = 0.0,
    ) -> None:
        self.model = (
            model
            or os.getenv("OLLAMA_MODEL")
            or DEFAULT_MODEL
        )

        self.base_url = (
            base_url
            or os.getenv("OLLAMA_BASE_URL")
            or DEFAULT_BASE_URL
        )

        self.llm = ChatOllama(
            model=self.model,
            base_url=self.base_url,
            temperature=temperature,
        )

    def generate_report(
        self,
        question: str,
        generated_sql: str,
        query_columns: tuple[str, ...],
        query_rows: tuple[tuple[object, ...], ...],
        row_count: int,
    ) -> str:
        messages = build_report_messages(
            question=question,
            generated_sql=generated_sql,
            query_columns=query_columns,
            query_rows=query_rows,
            row_count=row_count,
        )

        response = self.llm.invoke(messages)

        content = response.content

        if not isinstance(content, str):
            raise TypeError(
                "Expected string content from Ollama."
            )

        report = content.strip()

        if not report:
            raise ValueError(
                "LLM returned an empty business report."
            )

        return report